### ISSUE TITLE
Dec 1: An Introduction

### ISSUE THREAD

**Issue by duffee** [PDLPorters/pdlporters.github.com#22]
To get the ball rolling with collecting submissions for the Advent Calendar, I will add 24 Issues for people to claim. We can start organising the structure, fill in the gaps and discuss any questions raised.

As suggested, my first one is coming together in a [gist](https://gist.github.com/duffee/920b9a6d1f40d9d71833f9f4a0d33f37)
I'm filling in the last 20% today. Correct any mistakes in the comments here.

Why are introductions always the hardest to write?

**Comment by duffee** [comment]
The finished post is in the above gist now.

**Comment by duffee** [comment]
Created #32 to create the directory structure under **/content**

**Comment by mohawk2** [comment]
The 1 Dec posting is now live. This can be closed?
