### ISSUE TITLE
Dec 2: Santa's Cartographer Elf uses PDL

### ISSUE THREAD

**Issue by duffee** [PDLPorters/pdlporters.github.com#23]
Is this a good place for the more complete Introduction Demo and tour of PDL?

**Comment by duffee** [comment]
Let's kick off with something visual, the [Cartography demo](https://pdl.perl.org/?page=demos/cartography)

**Comment by mohawk2** [comment]
Now live.

**Comment by duffee** [comment]
That's actually a great catch-phrase _If you want to X, you need PDL!_

I may end up using that on _all_ my posts ;)
