### ISSUE TITLE
Use a modern renderer

### ISSUE THREAD

**Issue by jberger** [PDLPorters/pdlporters.github.com#4]
The original port of this site used raw jquery to avoid using server-side rendering. To achieve this, it made some attempt at being data driven and made some classes to do make that easier. At some later point I added rivets.js which is a front-end rendering tool in the vein of the data driven renderers of the modern era, but a fair bit simplistic. I also had no idea what I was doing.

Today I'd like to see the data simplified, those helper classes I created removed, and in the place of my old architecture, I'd probably use Vue js to render things using proper components. This will affect #3 given that the data format would change. It doesn't matter which would happen first but probably they shouldn't happen at the same time to avoid confusion.

**Comment by mohawk2** [comment]
> I'd probably use Vue js to render things using proper components

You did!
