### ISSUE TITLE
Dec 13: The Sound of Perl

### ISSUE THREAD

**Issue by HaraldJoerg** [PDLPorters/pdlporters.github.com#44]
The article has yet to be written!

I am using PDL as a synthesizer/sequencer to create sound data - and to show the waveform like in an oscilloscope, and the power spectrum of the sound.

For the advent calender, demo code will create a sawtooth wave, the one-liner to create the interactive plots is awesome.
I can also add a "barrel organ" piece which fits the season.

**Comment by mohawk2** [comment]
Sounds great! I've added you to the tracker on https://github.com/PDLPorters/pdl/issues/503

**Comment by mohawk2** [comment]
@HaraldJoerg Would you like a "bio" entry? If so please take a look in `statocles-site/site.yml` for the format and either PR it, or say here and I'll put it in.
