### ISSUE TITLE
Dec 19 - Optics - Ray Tracing with matrix multiplication

### ISSUE THREAD

**Issue by duffee** [PDLPorters/pdlporters.github.com#56]
Building on from Dec 16 where we used the `x` operator to do matrix multiplication, this article is a quick post on simple ray tracing using matrices.

Gives a shout out to jberger's Physics::RayTransfer module which has a nice OO interface, but no PDL

**Comment by duffee** [comment]
Almost there
https://gist.github.com/duffee/3a574827be9d3112491c2e52cbcc715a

**Comment by mohawk2** [comment]
Looking good! That last image seems broken at least in the gist?
