### ISSUE TITLE
Dec ?? - Hough transform for image feature extraction

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdlporters.github.com#58]
This will demonstrate an image feature extraction algorithm.

**Comment by duffee** [comment]
Finally, the metadata that we're looking for to decorate the post is:
* a banner file for the top of the post/calendar door - the image scales so no need to worry about the image size
* attribution info for the banner image - plain text or html is fine (I usually get it the same time that I get the image from https://search.creativecommons.org/ )
* author bio - 2 or 3 lines
* avatar - link to your github profile pic or gravatar link
* maybe some tag suggestions?

Get the post done first. We can fix the metadata retroactively if need be.
