### ISSUE TITLE
PDL::Demos gallery

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/pdlporters.github.com#9]
We should make a section (on the front page - @dhdeangelis fancy making this?) of a "PDL gallery" of demos. This would be a JavaScript query to the MetaCPAN API for all modules starting with `PDL::Demos::`, which is the namespace where those live. A recent PDL, where those were installed, would list them with the `demo` command.

A model for this JS exists already, with the "podviewer", and also our search drop-down.

**Comment by dhdeangelis** [comment]
Good idea, @mohawk2. I will have a look and see what I can do. I am not very proficient in JavaScript but can probe my way forward.

**Comment by mohawk2** [comment]
> Good idea, @mohawk2. I will have a look and see what I can do. I am not very proficient in JavaScript but can probe my way forward.

It's surprisingly easy! Please ask questions if you have them.

Also, the basis of an amazing demo of several modules would be https://scientiaplusconscientia.wordpress.com/2014/08/13/mapping-snowline-temperate-glacier-otsu-optimal-thresholding/ - any chance of creating such?

Further thinking about the gallery bit - we could make a convention of demo modules' synopsis showing `cpanm (module name)`, then `pdl> demo (demo name)`, and show the synopsis in the results if that can be easily extracted.

**Comment by mohawk2** [comment]
By the way, @zmughal - any chance of a PDL demo of Devel::IPerl? *That* would be powerful!

**Comment by dhdeangelis** [comment]
I start getting a grasp on how this works (not a JQuery master here). For example, adding:

`<search-results query="PDL::Demos"></search-results>`

to the file `index.html` within the _main content_ section, after <app-body> call gives a list of results after the two main paragraphs. A few of these results are true PDL::Demos, most others not, but I guess this can be sorted out somehow.

However, I believe that the page design will probably need to be adapted to make place for this section harmoniously. Is this something that should perhaps be addressed in concert with #15 and #16 ?

**Comment by mohawk2** [comment]
> However, I believe that the page design will probably need to be adapted to make place for this section harmoniously. Is this something that should perhaps be addressed in concert with #15 and #16 ?

I believe what Joel has in mind is that those issues will make our code, templates, etc easier to maintain / enhance. The page-design you're referring to would be such an enhancement. However, like all technical debt matters, it's a trade-off: do we feel the benefit of ripping out jQuery outweighs the cost of doing so (including the opportunity cost of not doing other things like making/improving a demo gallery)?

More immediately, @dhdeangelis what does `<search-results query="PDL::Demos"></search-results>` currently produce that it shouldn't? If we can tweak that towards being what it *should*, I think that would be a big win. It would certainly be worth making a new `<demo-gallery>` if needed with such tweaks; because we have no-one depending on the structure of our setup, we have freedom to refactor as we see fit when it becomes clearer what's needed.

**Comment by dhdeangelis** [comment]
> More immediately, @dhdeangelis what does `<search-results query="PDL::Demos"></search-results>` currently produce that it shouldn't? If we can tweak that towards being what it _should_, I think that would be a big win. It would certainly be worth making a new `<demo-gallery>` if needed with such tweaks; because we have no-one depending on the structure of our setup, we have freedom to refactor as we see fit when it becomes clearer what's needed.

Sure, below is what the line produces:

Search provided by [MetaCPAN](https://metacpan.org/)

Found 21 hits

[PDL::Demos](http://localhost:3000/index.html?docs=PDL::Demos) - PDL demo infrastructure

[PDL::Demos::PGPLOT](http://localhost:3000/index.html?docs=PDL::Demos::PGPLOT) - demonstrate PDL::Graphics::PGPLOT capabilities

[PDL::Demos::Gnuplot](http://localhost:3000/index.html?docs=PDL::Demos::Gnuplot) - demonstrate PDL::Graphics::Gnuplot capabilities

[PDL::Demos::PGPLOT_OO](http://localhost:3000/index.html?docs=PDL::Demos::PGPLOT_OO) - demonstrate PDL::Graphics::PGPLOT OO capabilities

[PDL::Demos::General](http://localhost:3000/index.html?docs=PDL::Demos::General) -

[PDL::Demos::Transform_demo](http://localhost:3000/index.html?docs=PDL::Demos::Transform_demo) -

[PDL::Demos::BAD_demo](http://localhost:3000/index.html?docs=PDL::Demos::BAD_demo) -

[PDL::Demos::TriD1](http://localhost:3000/index.html?docs=PDL::Demos::TriD1) -

[PDL::Demos::TriD2](http://localhost:3000/index.html?docs=PDL::Demos::TriD2) -

[PDL::Demos::TriDGallery](http://localhost:3000/index.html?docs=PDL::Demos::TriDGallery) -

[PDL::Demos::Cartography_demo](http://localhost:3000/index.html?docs=PDL::Demos::Cartography_demo) -

[PDL::FAQ](http://localhost:3000/index.html?docs=PDL::FAQ) - Frequently asked questions about PDL

[perldl](http://localhost:3000/index.html?docs=perldl) - Simple shell for PDL (see also pdl2)

[PDL::Tips](http://localhost:3000/index.html?docs=PDL::Tips) - Small tidbits of useful arcana. Programming tidbits and such.

[PDL::Transform::Cartography](http://localhost:3000/index.html?docs=PDL::Transform::Cartography) - Useful cartographic projections

[WebService::Plotly](http://localhost:3000/index.html?docs=WebService::Plotly) - access plot.ly programmatically

[PDL::Graphics](http://localhost:3000/index.html?docs=PDL::Graphics) - Introduction to the PDL::Graphics modules

[PDL::BadValues](http://localhost:3000/index.html?docs=PDL::BadValues) - Discussion of bad value support in PDL

[PDL::QuickStart](http://localhost:3000/index.html?docs=PDL::QuickStart) - Quick introduction to PDL features.

[PDL::Graphics::TriD::GObject](http://localhost:3000/index.html?docs=PDL::Graphics::TriD::GObject) - Simple Graph Objects for TriD

**Comment by mohawk2** [comment]
Sounds like what we'd need here, then, is an additional attribute on `<search-results>` of `prefix=`, here to be `PDL::Demos::`. I suspect the MetaCPAN API doesn't support such a concept, so we'd need to filter it in our JS?

**Comment by dhdeangelis** [comment]
The MetaCPAN API is very nice and flexible but I do not see a way there to restrict and filter results.

For example Searching for `<search-results query="PDL::Demos::Gnuplot"></search-results>` returns:

Search provided by [MetaCPAN](https://metacpan.org/)

Found 2 hits

[PDL::Demos::Gnuplot](http://localhost:3000/index.html?docs=PDL::Demos::Gnuplot) - demonstrate [PDL::Graphics](http://localhost:3000/index.html?docs=PDL::Graphics)::Gnuplot capabilities

PDL::Graphics - Introduction to the PDL::Graphics modules

**Comment by mohawk2** [comment]
The `search-results` pseudo-element is implemented in JavaScript on our site. I am proposing that by adding a `prefix` attribute to that, we could achieve what we want.

**Comment by dhdeangelis** [comment]
I just implemented a simple Demo gallery that works OK but looks ugly:
https://github.com/dhdeangelis/pdlporters.github.com/tree/hda
I could not make a GitHub page out of this. How should we preview this before doing a PR?

**Comment by mohawk2** [comment]
How about making another link in the left bar for "PDL Demos gallery (experimental)"? That would allow us to release early, release often :-)

Also, the work looks really promising! Is it possible to just add an optional `prefix` attribute to the existing `search-results`, rather than duplicating it?

**Comment by mohawk2** [comment]
Thank you!

**Comment by mohawk2** [comment]
I believe the "Demos" section is now pretty good; with the PDL::Graphics::Simple ability to use an environment variable to control device and output, and a harness to run all the scripts and parse their text and output, we now have 10+ there with fairly nice-looking plots and some animations.

@dhdeangelis Do you (as a second pair of eyes) agree it looks OK?

**Comment by dhdeangelis** [comment]
The Demos sections looks very nice, a lot nicer than before! The simplex demo is excellent. I have not had the time to look in detail though.  Excellent work @mohawk2 !

**Comment by mohawk2** [comment]
You're very kind! Thank you for all your work so far on the website.
